### ISSUE TITLE
Test for Redroid is failed by Timeout after 20 mins

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina#1797] opened 2022-07-27 12:26 UTC
Env.: Prod, Reprod test run

Steps:
1. Start Redroid test via automation 
2. Test is failed by timeout after 20 mins
`TEST [Test details test - redroidTest] FAILED at [11:24:16 2022-07-27] - Test run card not finished -  timeout exceeded

com.zebrunner.carina.demo.util.WaitUtil.waitElementMatchByCondition(WaitUtil.java:270)
com.zebrunner.carina.demo.gui.desktop.component.testrun.card.TestRunCard.waitFinish(TestRunCard.java:129)
com.zebrunner.carina.demo.gui.esg.TestDetailsTest.redroidTest(TestDetailsTest.java:191)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.base/java.lang.reflect.Method.invoke(Unknown Source)
org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.base/java.lang.Thread.run(Unknown Source)`
<img width="922" alt="Снимок экрана 2022-07-27 в 15 09 19" src="https://user-images.githubusercontent.com/32964663/181246236-a08e943b-680c-4f69-a7df-70f223428c76.png">

LInk for test run 
https://qps.zebrunner.com/projects/ZEB/test-runs/10468/tests/665115?runsState=eyIjIjpudWxsLCJwcm9qZWN0S2V5IjoiWkVCIiwiYWN0aXZlVGVzdFJ1bklkIjoxMDQ2OCwiYWN0aXZlUHJvamVjdCI6bnVsbH0%3D#log-86

**Comment by vdelendik** [comment] 2022-07-27 14:55
closing as not a bug

**Closed by vdelendik** 2022-07-27 14:55 UTC
Labels: bug, invalid
