### ISSUE TITLE
element.findExtendedElement(By by); don't look for child element from called parent element

### ISSUE THREAD

**Issue by DenisPitsul2020** [zebrunner/carina#1499] opened 2021-11-05 17:37 UTC
Expected:
Child element is searched inside the parent element.
Actual:
The element is searched from the root element.

The same sitiatin with element.findExtendedElements(By by).

**Comment by vdelendik** [comment] 2021-11-09 10:14
closing as not a bug

**Closed by vdelendik** 2021-11-09 10:14 UTC
Labels: bug, invalid
