### ISSUE TITLE
Carina 7.3.15. Selector [className or id] is recognized as [css selector]

### ISSUE THREAD

**Issue by dzmitry-pinchuk** [zebrunner/carina#1600] opened 2022-02-09 12:09 UTC
**Describe the bug**
Selector **className** or **id** is recognized as **css selector**

**Logs/Links**
On page component is described as
`@FindBy(className = "locator-with-class-name")
private someComponent popup;`
But test is failed with logs:
`org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".locator\-with\-class\-name"}`

```
@FindBy(id = "webWidget")
private HelpComponent helpComponent;
```
`org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#webWidget"}`

**Web (please complete the following information):**
 - Google Chrome 98
 - Carina 7.3.15

**Additional context**
Repro 100% with **className** and **id**

**Comment by vdelendik** [comment] 2022-02-18 18:06
closing as not a bug. repro on regular selenium which convert all kind of xpath to css when return any error message. actually provided xpath is used during communication with browser.

**Closed by vdelendik** 2022-02-18 18:06 UTC
Labels: bug, invalid
