### ISSUE TITLE
Web sample: Test case run with error message "FAIL: element 'brandLinks1 (By.xpath: //div[contains(@class, 'brandmenu-v2')]//a)' is not clicked!"

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina#1688] opened 2022-06-06 12:19 UTC
**Describe the bug**
Steps:
1)Launch Web demo test with Chrome=101 and branch 100-200
2)Verify that test run dosn't contain unexpected errors
Actual result: test case contains unexpected error message "FAIL: element 'brandLinks1 (By.xpath: //div[contains(@class, 'brandmenu-v2')]//a)' is not clicked!"
Expected: test run dosn't contain unexpected errors

**Logs/Links**
Test run with error https://olgatest32.zebrunner.org/projects/DEF/test-runs/621/tests/19316?runsState=eyIjIjpudWxsLCJwcm9qZWN0S2V5IjoiREVGIiwiYWN0aXZlVGVzdFJ1bklkIjo2MjEsImFjdGl2ZVByb2plY3QiOm51bGx9#log-7

**Web (please complete the following information):**
 - Browser Chrome
 - Version 101

**Comment by vdelendik** [comment] 2022-06-06 15:56
closing as won't fix. root cause already fixed in different ticket

**Closed by vdelendik** 2022-06-06 15:56 UTC
Labels: bug, invalid
