### ISSUE TITLE
callAPIWithRetry - Query parameter in request API is appended until condition is satisfied

### ISSUE THREAD

**Issue by harshalprkh** [zebrunner/carina#1954] opened 2022-11-24 12:38 UTC
Issue - When callAPIWithRetry method is used with certain condition, query parameter in the request API url is getting appended every time api is hit until the condition is satisfied.

JobGet job = new JobGet();
job.setHeaders("X-Auth-Token=" + R.CONFIG.get("X-Auth-Token"));
job.replaceUrlPlaceholder("schedule_id", schedule_id);
AtomicInteger counter = new AtomicInteger(0);
		
Optional<Response> res = job.callAPIWithRetry()
		.withLogStrategy(APIMethodPoller.LogStrategy.ALL)
		.peek(rs -> counter.getAndIncrement())
		.until(len -> JsonPath.read(job.callAPI().asString(), "$.jobs.length()").equals(1))
		.pollEvery(4, ChronoUnit.SECONDS)
		.stopAfter(2, ChronoUnit.MINUTES)
		.execute();

so for the above example till the condition (jobs.length) is satisfied, query parameter is getting appended

1st hit
URL - https://<env>/v1/jobs/schedule_id=1234&page_size=1

2nd hit
URL - https://<env>/v1/jobs/schedule_id=1234&schedule_id=1234&page_size=1&page_size=1

**Comment by akamarouski** [comment] 2022-11-25 10:06
Hi, @harshalprkh 
The problem is not reproduced. Try not to call the callAPI method in line 
`.until(len -> JsonPath.read(job.callAPI().asString(), "$.jobs.length()").equals(1))
`
In the len parameter you already get the response on every try. If this doesn't help, please let me know.

**Comment by harshalprkh** [comment] 2022-11-25 12:48
Hi @akamarouski,

I have tried removing callAPI method from line -
.until(len -> JsonPath.read(job.callAPI().asString(), "$.jobs.length()").equals(1)) but still facing the same problem.

Updated line of code -

JobGet job = new JobGet();
job.setHeaders("X-Auth-Token=" + R.CONFIG.get("X-Auth-Token"));
job.replaceUrlPlaceholder("schedule_id", schedule_id);

Optional res = job.callAPIWithRetry()
.withLogStrategy(APIMethodPoller.LogStrategy.ALL)
.until(len -> JsonPath.read(len.asString(), "$.jobs.length()").equals(1))
.pollEvery(4, ChronoUnit.SECONDS)
.stopAfter(2, ChronoUnit.MINUTES)
.execute();

**Comment by vdelendik** [comment] 2022-12-01 11:58
@harshalprkh, let's communicate in telegram channel. we need logs in DEBUG mode and seems like API method implementation to repro...

**Comment by harshalprkh** [comment] 2022-12-08 12:34
@vdelendik Let's connect and discuss.

**Comment by akamarouski** [comment] 2023-01-13 12:03
The problem has been reproduced

If set `@Endpoint(url = "${base_url}/users?aaaa=bbbb", methodType = HttpMethodType.POST)`
and in constructor set
` addUrlParameter("asdfdasf", "dsafadfsfd");`
URL will be for example:
`http://jsonplaceholder.typicode.com/users?test=test&aaaa=bbbb&aaaa=bbbb&aaaa=bbbb/11`

**Comment by akamarouski** [comment] 2023-01-13 12:28
wontfix
@harshalprkh  use addUrlParameter  method for adding all query params to the request, do not try to  construct the URL manually with query params

**Closed by akamarouski** 2023-01-13 12:28 UTC
Labels: bug
